### ISSUE TITLE
Makefile:94: recipe for target 'test' failed

### ISSUE THREAD

**Issue by bmabir17** [CatalystCode/faceanalysis#74]
I have tried to run 
`sudo make test`

But getting the following error

```
======================================================================
FAIL: test_end_to_end_with_different_file_formats (tests.test_api.ApiTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tests/test_api.py", line 180, in test_end_to_end_with_different_file_formats
    self._test_end_to_end_with_matching_imgs(fnames)
  File "/app/tests/test_api.py", line 113, in _test_end_to_end_with_matching_imgs
    self._wait_for_img_to_finish_processing(img_id)
  File "/app/tests/test_api.py", line 105, in _wait_for_img_to_finish_processing
    self.fail('Waited too long for image {}'.format(img_id))
AssertionError: Waited too long for image 11

======================================================================
FAIL: test_end_to_end_with_multiple_faces_per_img_that_match (tests.test_api.ApiTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tests/test_api.py", line 132, in test_end_to_end_with_multiple_faces_per_img_that_match
    self._test_end_to_end_with_matching_imgs(fnames)
  File "/app/tests/test_api.py", line 113, in _test_end_to_end_with_matching_imgs
    self._wait_for_img_to_finish_processing(img_id)
  File "/app/tests/test_api.py", line 105, in _wait_for_img_to_finish_processing
    self.fail('Waited too long for image {}'.format(img_id))
AssertionError: Waited too long for image 7

======================================================================
FAIL: test_end_to_end_with_one_face_per_img_that_match (tests.test_api.ApiTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tests/test_api.py", line 126, in test_end_to_end_with_one_face_per_img_that_match
    self._test_end_to_end_with_matching_imgs(fnames)
  File "/app/tests/test_api.py", line 113, in _test_end_to_end_with_matching_imgs
    self._wait_for_img_to_finish_processing(img_id)
  File "/app/tests/test_api.py", line 105, in _wait_for_img_to_finish_processing
    self.fail('Waited too long for image {}'.format(img_id))
AssertionError: Waited too long for image 1

======================================================================
FAIL: test_end_to_end_with_one_to_multiple_faces_per_img_that_match (tests.test_api.ApiTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tests/test_api.py", line 138, in test_end_to_end_with_one_to_multiple_faces_per_img_that_match
    self._test_end_to_end_with_matching_imgs(fnames)
  File "/app/tests/test_api.py", line 113, in _test_end_to_end_with_matching_imgs
    self._wait_for_img_to_finish_processing(img_id)
  File "/app/tests/test_api.py", line 105, in _wait_for_img_to_finish_processing
    self.fail('Waited too long for image {}'.format(img_id))
AssertionError: Waited too long for image 6

======================================================================
FAIL: test_upload_and_process_img_without_face (tests.test_api.ApiTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tests/test_api.py", line 144, in test_upload_and_process_img_without_face
    self._wait_for_img_to_finish_processing(img_id)
  File "/app/tests/test_api.py", line 105, in _wait_for_img_to_finish_processing
    self.fail('Waited too long for image {}'.format(img_id))
AssertionError: Waited too long for image 9

======================================================================
FAIL: test_upload_and_process_twice (tests.test_api.ApiTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tests/test_api.py", line 171, in test_upload_and_process_twice
    self._wait_for_img_to_finish_processing(img_id)
  File "/app/tests/test_api.py", line 105, in _wait_for_img_to_finish_processing
    self.fail('Waited too long for image {}'.format(img_id))
AssertionError: Waited too long for image 5

----------------------------------------------------------------------
Ran 12 tests in 376.599s

FAILED (failures=6, skipped=3)
Name                              Stmts   Miss  Cover
-----------------------------------------------------
faceanalysis/api.py                 107     11    90%
faceanalysis/auth.py                 49      3    94%
faceanalysis/domain/docker.py        58     15    74%
faceanalysis/domain/errors.py         8      0   100%
faceanalysis/domain/faceapi.py      136    136     0%
faceanalysis/face_matcher.py        101     71    30%
faceanalysis/face_vectorizer.py      31     16    48%
faceanalysis/log.py                  16      0   100%
faceanalysis/models.py               94      6    94%
faceanalysis/settings.py             27      2    93%
faceanalysis/storage.py              51     17    67%
faceanalysis/tasks.py                 9      1    89%
main.py                              36     36     0%
-----------------------------------------------------
TOTAL                               723    314    57%
WARNING: The FACE_API_MODEL_ID variable is not set. Defaulting to a blank string.
```

My .env file is the following
```
# these values configure the build of the docker images
BUILD_TAG=latest
DOCKER_REPO=cwolff
DEVTOOLS=false

# the port on which the api will be available
APP_PORT=9090

# paths to the directories where data will be persisted on disk
DATA_DIR=./persisted_data/prod/images
DB_DIR=./persisted_data/prod/database

# queue configuration
IMAGE_PROCESSOR_QUEUE=faceanalysis
RABBITMQ_USER=faceanalysistasks
RABBITMQ_PASSWORD=asd

# configuration values for mysql
MYSQL_USER=faceanalysisrw
MYSQL_PASSWORD=asd
MYSQL_ROOT_PASSWORD=asd
MYSQL_DATABASE=faceanalysis

# allowed values are DEBUG, INFO, WARNING, ERROR and CRITICAL
LOGGING_LEVEL=DEBUG

# separate multiple extensions with underscores
ALLOWED_IMAGE_FILE_EXTENSIONS=JPG_PNG

# api access token configuration
TOKEN_SECRET_KEY=some-long-random-string
DEFAULT_TOKEN_EXPIRATION_SECS=500

# maximum distance between two face vectors for them to be considered the same person
DISTANCE_SCORE_THRESHOLD=0.6

# docker image name of the algorithm to use for face vectorization
FACE_VECTORIZE_ALGORITHM=cwolff/faceanalysis_facerecognition

# face-api configuration, only used if FACE_VECTORIZE_ALGORITHM is set to "FaceApi"
FACE_API_GROUP_ID=
FACE_API_ACCESS_KEY=
FACE_API_REGION=
FACE_API_ENDPOINT=

# connection string for your docker daemon, on windows this should be tcp://0.0.0.0:2375
DOCKER_DAEMON=unix://var/run/docker.sock

```
my system 
```
Linux version 4.15.0-33-generic (buildd@lgw01-amd64-010) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #36~16.04.1-Ubuntu SMP Wed Aug 15 17:21:05 UTC 2018
```

**Comment by c-w** [comment]
Thanks for getting in touch. That error happens when the queue consumer isn't running (so the image never gets processed whence the test times out). Could you post the output of `docker-compose ps` and `docker-compose logs` when running the tests? This should show the worker container as running. Thanks!
